version: "3"

services:
  postgres:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=psql
      - POSTGRES_DB=auto

  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      - postgres
